### ISSUE TITLE
Cannot find module '/usr/src/app/node_modules/uglify-es'

### ISSUE THREAD

**Issue by jjacobs33589** [rossmartin/cordova-uglify#39] opened 2018-03-27 15:50 UTC
I've been using this plugin for awhile and it has worked great but ever since the latest update I always get the following error when I build my ionic project.

`Error: Cannot find module '/usr/src/app/node_modules/uglify-es'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object. (/usr/src/app/hooks/after_prepare/uglify.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
Error: Hook failed with error code 1: /usr/src/app/hooks/after_prepare/uglify.js`

I can fix this by going into the uglify.js file and updating line ten from 

`var UglifyJS = require(path.join(dependencyPath, 'uglify-es'));`

to 

`var UglifyJS = require(path.join(dependencyPath, 'uglify-js'));`

This changed with the latest update and makes so the projects no longer build. Can you push an update with this fixed?

**Comment by rossmartin** [comment] 2018-03-27 16:24
I think your node_modules still has a copy of the old version somehow or you have an npm version lower than 3. Can you please try uninstalling the package first and then do a fresh install?

`npm uninstall cordova-uglify`

and then try 

`npm install cordova-uglify`

What version of npm are you using?  `npm -v` will output it.

**Comment by jjacobs33589** [comment] 2018-03-27 17:54
Thank you for getting back to me so quickly! My npm version is 5.6.0
I tried uninstalling the plugin, deleting the node_modules folder entirely and doing an npm install.
Once that finished I installed the plugin again using npm install cordova-uglify and when I try to do a build I still have the same error from above.

**Comment by rossmartin** [comment] 2018-03-27 20:03
I checked out the UglifyJS2 repo and this statement prior to v3.3.15 has changed - 

It used to say - 

> To minify ECMAScript 2015 or above, use the `npm` package [**uglify-es**](https://github.com/mishoo/UglifyJS2/tree/harmony).

It now says - 

> To minify ECMAScript 2015 or above, transpile using tools like [Babel](https://babeljs.io/).

I wonder if the author has silently abandoned `uglify-es` and just prefers everyone to transpile their JS first before using `uglify-js`.  The reason I updated this package to use `uglify-es` was to support those not transpiling their JS to ES5 and be backwards compatible.  

In either situation, this package should be working as I've done an install on old and new cordova projects.  It is working for me today using `uglify-es` with no changes.  I'm using node v5.6.0 and npm v8.9.1 on mac OS 10.12.6

 I'm going to do some more investigating and I'll get back soon.  I may just revert back to having the package use `uglify-js` and mention that you'll need to make sure your JS is transpiled to ES5 first.

**Comment by rossmartin** [comment] 2018-03-27 22:54
@jjacobs33589 I see whats happening here.  If you already have `uglify-js` in your `node_modules` folder and then `npm install cordova-uglify` the `uglify-es` package is not being put into the `node_modules` folder for some reason.

I was able to reproduce by these steps -

1. create a new cordova project
1. install cordova-uglify and verify that it works by itself with nothing else ✅ 
1. uninstall cordova-uglify
1. install uglify-js
1. install cordova-uglify (and you'll notice you won't see uglify-es in node_modules, just uglify-js, wtf???).
1. try to build the app with a previous instance of uglify-js in node_modules after installing cordova-uglify results in what you are experiencing ❌

Something in your dependencies is using `uglify-js` and when that is in node_modules and for some reason `uglify-es` does not get put there when installing `cordova-uglify`.

**Comment by rossmartin** [comment] 2018-03-27 23:42
I've decided to abandon `uglify-es` and go back to using `uglify-js`.  This issue is resolved in 0.3.2 and as of this commit https://github.com/rossmartin/cordova-uglify/commit/eeb41a851fbf23b44439485885394d9e243fce9c

Unfortunately I don't think we're at the stage yet where most devices (webviews) can run ES6+ code.

If anyone is writing ES6+ in your cordova project make sure it is transpiled to ES5.  You'll want it to be transpiled before running this hook also.  I think this is a much safer approach for you and for this hook.

**Closed by rossmartin** 2018-03-27 23:42 UTC

**Comment by jjacobs33589** [comment] 2018-03-28 00:10
That sounds good, thank you so much!
I really appreciate your quick response!
